#!/usr/bin/env bash
# 配置 MySQL 5.7 增强半同步，并安装本机写入安全门禁服务。
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common_debian.sh
source "${SCRIPT_DIR}/../lib/common_debian.sh"

usage() {
    cat <<'EOF'
Usage: 02_configure_lossless_semisync.sh --config FILE [--apply] [--install-guard]

Without --apply, the script prints and validates the intended settings. With
--apply, it installs the semi-sync plugins and applies AFTER_SYNC. With
--install-guard, it also installs a systemd service/timer that sets the local
instance read-only whenever semi-sync is not operational or fewer than the
required number of semi-sync replicas are connected.
EOF
}

CONFIG_FILE=""
APPLY=false
INSTALL_GUARD=false
while [[ $# -gt 0 ]]; do
    case "$1" in
        --config) CONFIG_FILE="${2:?missing config file}"; shift 2 ;;
        --apply) APPLY=true; shift ;;
        --install-guard) INSTALL_GUARD=true; shift ;;
        -h|--help) usage; exit 0 ;;
        *) die "Unknown argument: $1" ;;
    esac
done
[[ -n "$CONFIG_FILE" ]] || { usage >&2; exit 1; }
load_secure_env "$CONFIG_FILE"
validate_config_keys "$CONFIG_FILE" MYSQL57_BASE_DIR MYSQL57_PORT MYSQL_ADMIN_USER MYSQL_ADMIN_PASSWORD SEMI_SYNC_WAIT_COUNT SEMI_SYNC_TIMEOUT_MS SEMI_SYNC_WAIT_POINT WRITE_FENCE_COMMAND
assert_port "$MYSQL57_PORT" || die "Invalid MYSQL57_PORT: $MYSQL57_PORT"
[[ "$SEMI_SYNC_WAIT_POINT" == "AFTER_SYNC" ]] || die "RPO=0 profile requires SEMI_SYNC_WAIT_POINT=AFTER_SYNC."
[[ "$SEMI_SYNC_WAIT_COUNT" =~ ^[1-9][0-9]*$ ]] || die "SEMI_SYNC_WAIT_COUNT must be a positive integer."
[[ "$SEMI_SYNC_TIMEOUT_MS" =~ ^[0-9]+$ ]] && (( SEMI_SYNC_TIMEOUT_MS >= 1000 && SEMI_SYNC_TIMEOUT_MS <= 4294967295 )) || die "SEMI_SYNC_TIMEOUT_MS must be 1000..4294967295."

ADMIN_CNF="/etc/mysql57-ha/admin.cnf"
GUARD_DIR="/usr/local/lib/mysql57-ha"
GUARD_SCRIPT="${GUARD_DIR}/semisync_write_guard.sh"
GUARD_SERVICE="mysql57-semisync-guard@${MYSQL57_PORT}.service"
GUARD_TIMER="mysql57-semisync-guard@${MYSQL57_PORT}.timer"

assert_admin_connection() {
    [[ -r "$ADMIN_CNF" ]] || die "Admin defaults file is absent: ${ADMIN_CNF}. Run 01_prepare_instance.sh first."
    mysql_exec "$ADMIN_CNF" 'SELECT 1' >/dev/null
}

persist_semisync_config() {
    require_root
    install -d -m 0750 -o root -g mysql /etc/mysql57/conf.d
    cat > /etc/mysql57/conf.d/20-semisync.cnf <<EOF
[mysqld]
rpl_semi_sync_master_enabled=ON
rpl_semi_sync_slave_enabled=ON
rpl_semi_sync_master_wait_for_slave_count=${SEMI_SYNC_WAIT_COUNT}
rpl_semi_sync_master_timeout=${SEMI_SYNC_TIMEOUT_MS}
rpl_semi_sync_master_wait_point=AFTER_SYNC
EOF
    chmod 0640 /etc/mysql57/conf.d/20-semisync.cnf
    chown root:mysql /etc/mysql57/conf.d/20-semisync.cnf
}

apply_semisync() {
    local plugin_dir
    plugin_dir="$(mysql_exec "$ADMIN_CNF" "SELECT @@plugin_dir")"
    [[ -f "${plugin_dir}/semisync_master.so" ]] || die "semisync_master.so not found under ${plugin_dir}"
    [[ -f "${plugin_dir}/semisync_slave.so" ]] || die "semisync_slave.so not found under ${plugin_dir}"

    mysql_exec "$ADMIN_CNF" "INSTALL PLUGIN rpl_semi_sync_master SONAME 'semisync_master.so';" 2>/dev/null || true
    mysql_exec "$ADMIN_CNF" "INSTALL PLUGIN rpl_semi_sync_slave SONAME 'semisync_slave.so';" 2>/dev/null || true

    persist_semisync_config

    mysql_exec "$ADMIN_CNF" "
SET GLOBAL rpl_semi_sync_master_enabled=ON;
SET GLOBAL rpl_semi_sync_slave_enabled=ON;
SET GLOBAL rpl_semi_sync_master_wait_for_slave_count=${SEMI_SYNC_WAIT_COUNT};
SET GLOBAL rpl_semi_sync_master_timeout=${SEMI_SYNC_TIMEOUT_MS};
SET GLOBAL rpl_semi_sync_master_wait_point='AFTER_SYNC';
SET GLOBAL sync_binlog=1;
SET GLOBAL innodb_flush_log_at_trx_commit=1;
"

    local status wait_point
    status="$(mysql_exec "$ADMIN_CNF" "SHOW VARIABLES LIKE 'rpl_semi_sync_master_wait_point'" | awk '{print $2}')"
    wait_point="$status"
    [[ "$wait_point" == "AFTER_SYNC" ]] || die "Failed to set rpl_semi_sync_master_wait_point=AFTER_SYNC"
    log_info "Enhanced semi-sync settings applied. Do not enable application writes until a replica is connected and the guard reports healthy."
}

install_guard() {
    require_root
    install -d -m 0750 "$GUARD_DIR"
    cat > "$GUARD_SCRIPT" <<EOF
#!/usr/bin/env bash
set -euo pipefail
# Generated by mysql57_orchestrator_ha/02_configure_lossless_semisync.sh
# shellcheck source=/dev/null
source '${CONFIG_FILE}'
# shellcheck source=/dev/null
source '${SCRIPT_DIR}/../lib/common_debian.sh'

ADMIN_CNF='${ADMIN_CNF}'
required='${SEMI_SYNC_WAIT_COUNT}'
status=\$(mysql_exec "\$ADMIN_CNF" "SHOW STATUS LIKE 'Rpl_semi_sync_master_status'" | awk '{print \$2}')
clients=\$(mysql_exec "\$ADMIN_CNF" "SHOW STATUS LIKE 'Rpl_semi_sync_master_clients'" | awk '{print \$2}')
clients=\${clients:-0}

if [[ "\$status" != "ON" || ! "\$clients" =~ ^[0-9]+$ || \$clients -lt \$required ]]; then
    log_error "Semi-sync safety gate failed: status=\${status:-unknown}, clients=\$clients, required=\$required. Fencing writes."
    mysql_exec "\$ADMIN_CNF" 'SET GLOBAL super_read_only=ON; SET GLOBAL read_only=ON;'
    '${WRITE_FENCE_COMMAND}' "semisync-not-operational" || true
    exit 1
fi
EOF
    chmod 0750 "$GUARD_SCRIPT"

    cat > "/etc/systemd/system/${GUARD_SERVICE}" <<EOF
[Unit]
Description=MySQL 5.7 semi-sync write safety gate for port ${MYSQL57_PORT}
After=network-online.target

[Service]
Type=oneshot
ExecStart=${GUARD_SCRIPT}
EOF

    cat > "/etc/systemd/system/${GUARD_TIMER}" <<EOF
[Unit]
Description=Run MySQL 5.7 semi-sync write safety gate every second

[Timer]
OnBootSec=15s
OnUnitActiveSec=1s
AccuracySec=1s
Unit=${GUARD_SERVICE}

[Install]
WantedBy=timers.target
EOF
    systemctl daemon-reload
    systemctl enable --now "$GUARD_TIMER"
    log_info "Installed semi-sync safety gate timer: ${GUARD_TIMER}"
}

assert_debian12
assert_admin_connection
if [[ "$APPLY" == true ]]; then
    apply_semisync
else
    log_info "Validated semi-sync profile: wait point=${SEMI_SYNC_WAIT_POINT}, replicas required=${SEMI_SYNC_WAIT_COUNT}, timeout=${SEMI_SYNC_TIMEOUT_MS}ms"
fi
[[ "$INSTALL_GUARD" == true ]] && install_guard
